### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by lepatrick714** [ReflexCS180/ReflexManagment#29]

**Comment by lepatrick714** [comment]
<img width="747" alt="screen shot 2017-11-03 at 3 31 34 pm" src="https://user-images.githubusercontent.com/14812977/32398367-191ee744-c0ac-11e7-82e5-63021012dcdf.png">

Just add buttons and other components for now. (Wireframe really)

**Comment by jonei005** [comment]
I would like to note that we should probably only focus on the main parts of the card.

* Name
* Column (list) that it came from
* Description
* Comments (text only)
* Created by
* Move (can be used in place of drag and drop: just select a new column to put the card in)

Also we can do simplified versions of stuff. Instead of copying Trello exactly on things like clicking on the title to change it, it might be easier to just add a button on the side called "Rename" or something.
